---
- name: Copy over config_panic_nodes.py
  copy:
    src: config_panic_nodes.py
    dest: /usr/local/bin/config_panic_nodes.py
    mode: 0755
    owner: root
    group: root

- name: Configure PANIC with config_panic_nodes.py
  script:
    cmd: config_panic_nodes.py --config_file {{ config_file }} --operation add --node_name {{ node_name }} --node_rpc_url {{ hostname }} --node_rpc_port {{ rpc_port }} --node_is_validator {{ is_validator }} --include_in_node_monitor {{ include_in_node_monitor }} --include_in_network_monitor {{ include_in_network_monitor }}
    become_user: panic

- name: Restart PANIC
  systemd:
    name: panic-cosmos.service
    state: restarted
